#!/usr/bin/with-contenv bash

if [ ${USERNAME} ] && [ ${USERNAME} != "abc" ]
then
    echo "Change login name"
    usermod -l ${USERNAME} abc
    groupmod -g ${USERNAME} abc
    echo "Change init scripts which use hardcoded username"
    find /etc/cont-init.d -type f ! -name 09-changeuser ! -name 40-move-home -exec sed -i "s/abc/${USERNAME}/g" {} \;
    echo "Change code-server startup script"
    sed -i "s/abc/${USERNAME}/g" /etc/services.d/code-server/run
else
    export USERNAME=abc
fi


