#!/usr/bin/with-contenv bash

# Overwrites default 10-adduser provided by linuxserver/docker-code-server

PUID=${PUID:-911}
PGID=${PGID:-911}

if [ -z ${USERNAME} ]
then
    export USERNAME=abc
fi

usermod -l ${USERNAME} abc
groupmod -g ${USERNAME} abc

groupmod -o -g "$PGID" "$USERNAME"
usermod -o -u "$PUID" "$USERNAME"

echo '
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------'
if [[ -f /donate.txt ]]; then
    echo '
To support the app dev(s) visit:'
    cat /donate.txt
fi
echo '
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------'
echo "
User uid:    $(id -u "$USERNAME")
User gid:    $(id -g "$USERNAME")
-------------------------------------
"
chown "$USERNAME":"$USERNAME" /app
chown "$USERNAME":"$USERNAME" /config
chown "$USERNAME":"$USERNAME" /defaults

