#!/usr/bin/with-contenv bash

if [ -z ${USERNAME} ]
then
    export USERNAME=abc
fi

if [ -z ${USER_HOME} ] && [ ${USER_HOME} != "/config" ]
then
    usermod -d ${USER_HOME} ${USERNAME}
    mv /config/{{extensions,data,workspace,.ssh}
    if [ -d /config/.config/code-server ]
    then
        mkdir -p ${USER_HOME}/.config/code-server
        mv /config/.config/code-server ${USER_HOME}/.config
    fi
    if [ -d /config/.local/share/code-server ]
    then
        mkdir -p ${USER_HOME}/.local/share/code-server
        mv /config/.local/share/code-server ${USER_HOME}/.local/share
    fi
fi
