#!/usr/bin/with-contenv bash

echo "**** installing java 16 from adoptopenjdk ****"
if ! dpkg -l | grep -e gnupg -e apt-transport-https > /dev/null; then
    apt-get update && apt-get install -y gnupg apt-transport-https
fi

[[ ! -f "/etc/apt/sources.list.d/adoptopenjdk.list" ]] && \
    curl -s https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | gpg --no-default-keyring --keyring ./adoptopenjdk-keyring.gpg --import - && \
    gpg --no-default-keyring --keyring ./adoptopenjdk-keyring.gpg --export --output /usr/share/keyrings/adoptopenjdk-archive-keyring.gpg && \
    echo 'deb [signed-by=/usr/share/keyrings/adoptopenjdk-archive-keyring.gpg] https://adoptopenjdk.jfrog.io/adoptopenjdk/deb bionic main' \
        > /etc/apt/sources.list.d/adoptopenjdk.list

