#!/usr/bin/with-contenv bash

echo "**** installing neovim stable from github ****"
if ! dpkg -l | grep -e wget > /dev/null; then
    apt-get update && apt-get install -y wget
fi

wget -c https://github.com/neovim/neovim/releases/download/v0.5.0/nvim-linux64.tar.gz -O - | tar -xz --strip-components=1 -C /usr
